config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :comments

  resources :users, shallow: true do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @users = User.all
  end

  def show

  end

  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.create(comment_params)
    redirect_to user_path(@user)
 
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)
 
    @user.save
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Listing comments</h1>
 
<table>
  <tr>
    <th>Username</th>
    <th>Comments</th>
    <th></th>
  </tr>
 

</table>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_with scope: :comment, url: comments_path, local: true do |form| %>

  <p>
  
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>

    <%= form.submit params[:user_id] %>
  </p>
<% end %>

app/views/comments/show.html.erb
<p>DDDSas</p>

app/views/home/index.html.erb
<h1>Directory</h1>
<div><%= link_to 'Users', controller: 'users' %></div>

<div><%= link_to 'Comments', controller: 'comments' %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Listing users</h1>
 
<table>
  <tr>
    <th>Username</th>
    <th></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= link_to 'Show all', user_path(user) %></td>
      <td><%= link_to 'Add comment', new_comment_path(:comment => { :user_id => user.id }) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with scope: :user, url: users_path, local: true do |form| %>
  <p>
    <%= form.label :Username %><br>
    <%= form.text_field :username %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<% @user.comments.each do |comment| %>
  <p>
    <strong>:FJJ</strong>
    <%= comment.body %>
  </p>
 
<% end %>


<%= link_to 'Back', users_path %>